[package]
name = "sevidor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = "*"
futures-util = "0.3.17"
tokio = {version = "1.14.0", features = ["macros", "rt-multi-thread"]}